### ISSUE TITLE
Need you help!!!Please

### ISSUE THREAD

**Issue by RiderLai** [arshadshk/SAINT-pytorch#1]
Hello!
I read the "Towards an Appropriate Query, Key, and Value Computation for Knowledge Tracing" paper.
In proposed model -> deep self-attentive encoder-decoder section, I look this
```The decoder takes  O and another sequential input Re= [S,Re1,···,Rek−1]of response embeddings with the start token embeddingS,```
I do not know this S and I can not find about s in the code.

I very want to  know that what is the S.
Please!

**Comment by arshadshk** [comment]
Hey,
It's nothing but the SOS token, that is the 'Start-of-Sequence' token. 
Have a look at- https://datascience.stackexchange.com/questions/26947/why-do-we-need-to-add-start-s-end-s-symbols-when-using-recurrent-neural-n

It won't be there in the code as there is no data loader class in the code. Usually while generating the response [S,Re1,···,Rek−1] we add this token at the start. ( In easy words, it's nothing but a unique numeric you add at the start of each input response list .)

**Comment by RiderLai** [comment]
Thank you very much!
Now, I understanded.XDD
