### ISSUE TITLE
Performance on EdNet

### ISSUE THREAD

**Issue by clara2911** [arshadshk/SAINT-pytorch#3]
Hi!

Thank you for this very understandable and well-documented implementation of SAINT. 
As I understand, you are not one of the authors of the original paper, am I correct? Did you test the performance (e.g. AUC) on public datasets - e.g. EdNet, of this specific model? If you know, it would help me a lot if you could include this in your README for example. Thanks in advance!

**Comment by arshadshk** [comment]
Hey,
Yes, am not an author of SAINT paper 😁. 
The AUC score for this model was around 77 (in the paper it's 78.11), though my training was not very exhaustive and it was just trained with the same hyperparameters as mentioned in the paper.

**Comment by clara2911** [comment]
Perfect, thanks for the quick answer!

**Comment by clara2911** [comment]
Hi @arshadshk one more question. Would you be able to add your code for running your model on EdNet as well - besides the example on random data? I can imagine it would also be a nice addition to this repo in general
